### ISSUE TITLE
Guild view command crashes after a few seconds

### ISSUE THREAD

**Issue by JanRuettinger** [guildai/guildai#205]
Whenever I run the command `guild view` to access the web gui I get the following error message:

 ```cmd
Traceback (most recent call last):
  File "xxxxxxxxxx/anaconda3/envs/tf_for_cv/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "xxxxxxxxxx/anaconda3/envs/tf_for_cv/lib/python3.8/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "xxxxxxxxxx/anaconda3/envs/tf_for_cv/lib/python3.8/site-packages/guild/serving_util.py", line 124, in app
    return dispatch(routes, env, start_resp)
  File "xxxxxxxxxx/anaconda3/envs/tf_for_cv/lib/python3.8/site-packages/guild/serving_util.py", line 113, in dispatch
    return handler(*args, **kw)(env, start_resp)
  File "xxxxxxxxxx/anaconda3/envs/tf_for_cv/lib/python3.8/site-packages/guild/view.py", line 269, in handle
    (time, stream, line) for time, stream, line in self._output.read(start, end)
  File "xxxxxxxxxx/anaconda3/envs/tf_for_cv/lib/python3.8/site-packages/guild/util.py", line 887, in read
    self._read_next(end)
  File "xxxxxxxxxx/anaconda3/envs/tf_for_cv/lib/python3.8/site-packages/guild/util.py", line 908, in _read_next
    time, stream = struct.unpack("!QB", index.read(9))
struct.error: unpack requires a buffer of 9 bytes
```

**Comment by gar1t** [comment]
It looks like one of the output files for a run is corrupt. I expect that this is happening because of a specific run. To work around this issue, you'd need to identify that run and move it out of the current runs list. You can use something like `guild export --move saved-runs` to do that.

I'm marking this as a bug as Guild should not crash when this happens but print an error message with the offending run.

**Comment by JanRuettinger** [comment]
Thanks for your help! I have printed the path of the run dir when the issue occurred and noticed that only ongoing runs produce the issue.

**Comment by gar1t** [comment]
Ah yes, that'd be a bug. Guild doesn't synchronize reads/writes across processes on those files. We'll get this fixed in the followup to 0.7. Thanks for the report and investigating the issue!

**Comment by JanRuettinger** [comment]
I am now on version `0.7.0.post1` but the error remains. 

error: 
```
(time, stream, line) for time, stream, line in self._output.read(start, end)
File ".../envs/tf_for_cv/lib/python3.8/site-packages/guild/util.py", line 887, in read
    self._read_next(end)
File ".../lib/python3.8/site-packages/guild/util.py", line 908, in _read_next
   time, stream = struct.unpack("!QB", index.read(9))
   struct.error: unpack requires a buffer of 9 bytes
```

The error occurs when there are experiments which are still running.

**Comment by gar1t** [comment]
This is not fixed yet. I'll update here when a fix is available.
