### ISSUE TITLE
Documentation: Mistakes & broken link

### ISSUE THREAD

**Issue by nalepae** [guildai/guildai#91]
1. On [this page](https://guild.ai/docs/start/optimization/):

`Next, run a search that includes two values for x and two values for noise:`

should be `three values for x`, not `two`.

2. On [this page](https://guild.ai/):
Link `Get started with Grid Search` is broken.

3. On [this page](https://guild.ai/docs/start/):
`$ guild compare --csv` outputs:

```
guild: --csv option requires an argument
```

And for information:

`$ guild compare --csv output.csv` outputs:
```
Traceback (most recent call last):
  File "/Users/emmanuelnalepa/miniconda3/bin/guild", line 10, in <module>
    sys.exit(main())
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/main_bootstrap.py", line 38, in main
    guild.main.main()
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/main.py", line 32, in main
    _main()
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/main.py", line 38, in _main
    main_cmd.main(standalone_mode=False)
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 759, in __call__
    return self.main(*args, **kwargs)
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 714, in main
    rv = self.invoke(ctx)
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 1132, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 951, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/external/click/core.py", line 552, in invoke
    return callback(*args, **kwargs)
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/click_util.py", line 146, in fn
    return fn0(*(args + (Args(**kw),)))
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/commands/compare.py", line 177, in compare
    compare_impl.main(args)
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/commands/compare_impl.py", line 62, in main
    _write_csv(args)
  File "/Users/emmanuelnalepa/miniconda3/lib/python3.6/site-packages/guild/commands/compare_impl.py", line 102, in _write_csv
    writer.writerow(row)
TypeError: a bytes-like object is required, not 'str'
```

4. On [this page](https://guild.ai/docs/start/optimization/):
`$ guild run train.py x=[-0.5,-0.4,-0.3,-0.2,-0.1]` outputs:
```
zsh: no matches found: x=[-0.5,-0.4,-0.3,-0.2,-0.1]
```

but `$ guild run train.py 'x=[-0.5,-0.4,-0.3,-0.2,-0.1]'` works.

(I tested in on macOS Mojave & Ubuntu 18.04, with iTerm2, with ZSH and ohmyzsh.
Works well with Ubuntu 18.04 on bash)

5. On [this page](https://guild.ai/docs/start/optimization/):

`$ guild run train.py x=[-0.25,-0.30,-0.35] noise=[0.0,0.1]` does not work for me, but
`$ guild run train.py 'x=[-0.25,-0.30,-0.35]' 'noise=[0.0,0.1]'` does.

(`$ guild run train.py 'x=[-0.25,-0.30,-0.35] noise=[0.0,0.1]'` does NOT work.)

6. In STYLE.md:

> "Guild AI Sytle Guide" 

Sytle --> Style

> Nonetheless, if something can be accomplished using builtin Python types and functions

It seems this sentence miss an end.

**Comment by gar1t** [comment]
Thank you very much! I missed the bug in `compare`. Marking as this as a bug accordingly.

The `compare` bug will be resolved for 0.7.

**Comment by gar1t** [comment]
Fix is available in 0.7.0. Thanks again!

**Comment by pseeth** [comment]
For what it's worth, I think the site documentation is still wrong. Also just tried it and got the same error, I had to add the single quotes around it to work.

**Comment by gar1t** [comment]
Let's actually fix these then.

In reference to the bugs you list above:

1. The new optimization section of the get started tutorial is [here](https://my.guild.ai/start/optimize). I believe the specified count is correctly three now.

2. The main Guild page no longer has that link. The links that I see there are all working.

3. I can't recreate this bug and neither can [our tests](https://github.com/guildai/guildai/blob/master/guild/tests/uat/simple-example.md) across 16 different platforms. If you're still seeing this could you please provide the version of Guild and platform details? (Use `guild check` for this).

4. The docs in general don't highlight the need to quote square brackets in `zsh`. They should. I'll open a separate ticket for that.

5. All fixed!

If you spot anything that we've missed here, please point that out so we can fix it. Otherwise if you think these topics are addressed, please feel free to close the issue. Thanks a lot for following up on this!
